apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: crawler
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      volumes:
      - name: cache-volume
        emptyDir: {}
      containers:
      - image: docker.io/bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-1
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        envFrom:
          - configMapRef:
              name: synergychat-crawler-configmap
      - image: docker.io/bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-2
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        env:
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS # The key to fetch.
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_2
      - image: docker.io/bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-3
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        env:
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS # The key to fetch.
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_3